export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const GET_USER = 'GET_USER';
export const VIEW_ACCT = 'VIEW_ACCT';
export const VIEW_TRANSACTIONS = 'VIEW_TRANSACTION';
export const GET_NODE_ID = 'GET_NODE_ID';
export const SUBMIT_TRANS = 'SUBMIT_TRANS';
